In [0]:
"""
            Checkpoint
- help to save intermediate results from failure
Ex will be implemented below:
    1. read data using auto loader
    2. run query and save data in table in memory without checkpoint
    3. run query and save data in table in memory with checkpoint (save intermediate results in in dbfs)

    4. cancel two query to run
    5. add new files to path query readstream from
    6. run 2 queries again

Conclusion:
the query without checkpoint, will run or read data from scratch the previous data 
"""

In [0]:
dbutils.fs.ls("dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/")

Out[1]: [FileInfo(path='dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/_schemas/', name='_schemas/', size=0, modificationTime=1694498223000),
 FileInfo(path='dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/attrition_04.csv', name='attrition_04.csv', size=11523, modificationTime=1694502481000),
 FileInfo(path='dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/attrition_05.csv', name='attrition_05.csv', size=11447, modificationTime=1694673949000),
 FileInfo(path='dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/attrition_06.csv', name='attrition_06.csv', size=11608, modificationTime=1694673949000)]

In [0]:
dbutils.fs.rm("dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/attrition_05.csv")

dbutils.fs.rm("dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/attrition_06.csv")

Out[8]: True

In [0]:
dbutils.fs.ls("dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/")

Out[9]: [FileInfo(path='dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/_schemas/', name='_schemas/', size=0, modificationTime=1694498223000),
 FileInfo(path='dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/attrition_04.csv', name='attrition_04.csv', size=11523, modificationTime=1694502481000)]

In [0]:
"""
                                Auto Loader
- format("cloudFiles"): Auto loader provides structured streaming source called cloud files
when specify, automatically process new file when arrive/incrementally process the data
- schema: specify location to track the schema of files 
- load: specify dir location which we read data from 
- schemaHints: without specify it make all columns string but need some columns to be int or float
to able to make calculalations
"""
attr_stream_data = spark.readStream.format("cloudFiles")\
    .option("cloudFiles.format", "csv")\
        .option("cloudFiles.schemaLocation", "dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/")\
            .option("cloudFiles.schemaHints", "Age int, DailyRate int, DistanceFromHome int, HourlyRate int, MonthlyIncome int, PercentSalaryHike int, YearsSinceLastPromotion int, YearsWithCurrManager int")\
                .load("dbfs:/FileStore/shared_uploads/auto_loader_streaming/attrition_source_stream/")

attr_stream_data.display()

Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,EducationField,Gender,HourlyRate,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,OverTime,PercentSalaryHike,PerformanceRating,YearsSinceLastPromotion,YearsWithCurrManager,_rescued_data
41,No,Travel_Rarely,334,Sales,2,Life Sciences,Male,88,4,Manager,2,Single,16015,No,19,3,0,4,null
18,No,Travel_Rarely,812,Sales,10,Medical,Female,69,1,Sales Representative,3,Single,1200,No,12,3,0,0,null
28,No,Travel_Rarely,1476,Research & Development,16,Medical,Male,68,2,Healthcare Representative,1,Single,5661,No,19,3,0,7,null
31,No,Travel_Rarely,218,Sales,7,Technical Degree,Male,100,2,Sales Executive,4,Married,6929,No,11,3,7,7,null
39,No,Travel_Rarely,1132,Research & Development,1,Medical,Male,48,3,Healthcare Representative,4,Divorced,9613,No,17,3,3,7,null
36,No,Non-Travel,1105,Research & Development,24,Life Sciences,Female,47,2,Laboratory Technician,2,Married,5674,No,15,3,0,8,null
32,No,Travel_Rarely,906,Sales,7,Life Sciences,Male,91,2,Sales Executive,3,Married,5484,No,14,3,4,8,null
38,No,Travel_Rarely,849,Research & Development,25,Life Sciences,Female,81,3,Research Director,2,Married,12061,No,17,3,0,1,null
58,No,Non-Travel,390,Research & Development,1,Life Sciences,Male,32,2,Healthcare Representative,3,Divorced,5660,Yes,13,3,1,2,null
31,No,Travel_Rarely,691,Research & Development,5,Technical Degree,Male,86,1,Research Scientist,4,Married,4821,Yes,12,3,0,3,null
31,No,Travel_Rarely,106,Human Resources,2,Human Resources,Male,62,2,Human Resources,1,Married,6410,No,12,3,1,0,null
45,No,Travel_Frequently,1249,Research & Development,7,Life Sciences,Male,97,3,Laboratory Technician,1,Divorced,5210,No,18,3,9,11,null
31,No,Travel_Rarely,192,Research & Development,2,Life Sciences,Male,32,1,Research Scientist,4,Divorced,2695,Yes,18,3,2,2,null
33,No,Travel_Frequently,553,Research & Development,5,Life Sciences,Female,74,3,Manager,2,Married,11878,No,11,3,8,8,null
39,No,Travel_Rarely,117,Research & Development,10,Medical,Male,99,4,Manager,1,Married,17068,Yes,14,3,11,10,null
43,No,Travel_Frequently,185,Research & Development,10,Life Sciences,Female,33,1,Laboratory Technician,4,Single,2455,No,19,3,1,7,null
49,No,Travel_Rarely,1091,Research & Development,1,Technical Degree,Female,90,4,Healthcare Representative,3,Single,13964,Yes,12,3,0,7,null
52,Yes,Travel_Rarely,723,Research & Development,8,Medical,Male,85,2,Research Scientist,2,Married,4941,No,15,3,7,7,null
27,No,Travel_Rarely,1220,Research & Development,5,Life Sciences,Female,85,1,Research Scientist,2,Single,2478,Yes,12,3,1,2,null
32,No,Travel_Rarely,588,Sales,8,Technical Degree,Female,65,2,Sales Executive,2,Married,5228,Yes,11,3,11,9,null
27,No,Travel_Rarely,1377,Sales,2,Life Sciences,Male,74,2,Sales Executive,3,Single,4478,Yes,11,3,0,4,null
31,No,Travel_Rarely,691,Sales,7,Marketing,Male,73,2,Sales Executive,4,Divorced,7547,No,12,3,1,7,null
32,No,Travel_Rarely,1018,Research & Development,2,Medical,Female,74,2,Research Scientist,4,Single,5055,No,16,3,0,7,null
28,Yes,Travel_Rarely,1157,Research & Development,2,Medical,Male,84,1,Research Scientist,4,Married,3464,Yes,13,3,2,2,null
30,No,Travel_Rarely,1275,Research & Development,28,Medical,Female,64,2,Research Scientist,4,Married,5775,No,13,3,1,9,null
31,No,Travel_Frequently,798,Research & Development,7,Life Sciences,Female,48,3,Manufacturing Director,3,Married,8943,No,24,4,8,9,null
39,No,Travel_Frequently,672,Research & Development,7,Medical,Male,54,5,Manager,4,Married,19272,No,15,3,13,3,null
39,Yes,Travel_Rarely,1162,Sales,3,Medical,Female,41,2,Sales Executive,3,Married,5238,Yes,18,3,0,0,null
33,No,Travel_Frequently,508,Sales,10,Marketing,Male,46,2,Sales Executive,4,Single,4682,No,14,3,0,1,null
47,No,Travel_Rarely,1482,Research & Development,5,Life Sciences,Male,42,5,Research Director,3,Married,18300,No,11,3,1,1,null
43,No,Travel_Frequently,559,Research & Development,10,Life Sciences,Female,82,2,Laboratory Technician,3,Divorced,5257,No,11,3,0,0,null
27,No,Non-Travel,210,Sales,1,Marketing,Male,73,2,Sales Executive,2,Married,6349,Yes,13,3,1,4,null
54,No,Travel_Frequently,928,Research & Development,20,Life Sciences,Female,31,2,Research Scientist,3,Single,4869,No,12,3,0,3,null
43,No,Travel_Rarely,1001,Research & Development,7,Life Sciences,Female,43,3,Healthcare Representative,1,Married,9985,No,16,3,0,0,null
45,No,Travel_Rarely,549,Research & Development,8,Other,Male,75,2,Research Scientist,4,Married,3697,No,14,3,9,8,null
40,No,Travel_Rarely,1124,Sales,1,Medical,Male,57,2,Sales Executive,4,Married,7457,Yes,22,4,0,2,null
29,Yes,Travel_Rarely,318,Research & Development,8,Other,Male,77,1,Laboratory Technician,1,Married,2119,Yes,11,3,0,7,null
29,No,Travel_Rarely,738,Research & Development,9,Other,Male,30,1,Laboratory Technician,4,Single,3983,No,17,3,2,2,null
30,No,Travel_Rarely,570,Sales,5,Marketing,Female,30,2,Sales Executive,3,Divorced,6118,No,13,3,1,2,null
27,No,Travel_Rarely,1130,Sales,8,Marketing,Female,56,2,Sales Executive,2,Married,6214,No,18,3,0,7,null
37,No,Travel_Rarely,1192,Research & Development,5,Medical,Male,61,2,Manufacturing Director,4,Divorced,6347,No,16,3,0,4,null
38,No,Travel_Rarely,343,Research & Development,15,Life Sciences,Male,92,3,Research Director,4,Divorced,11510,Yes,14,3,2,9,null
31,No,Travel_Rarely,1232,Research & Development,7,Medical,Female,39,3,Manufacturing Director,4,Single,7143,Yes,14,3,4,10,null
29,No,Travel_Rarely,144,Sales,10,Marketing,Female,39,2,Sales Executive,2,Divorced,8268,Yes,14,3,1,7,null
35,No,Travel_Rarely,1296,Research & Development,5,Technical Degree,Male,62,3,Manufacturing Director,2,Single,8095,No,13,3,0,13,null
23,No,Travel_Rarely,1309,Research & Development,26,Life Sciences,Male,83,1,Research Scientist,4,Divorced,2904,No,12,3,0,2,null
41,No,Travel_Rarely,483,Research & Development,6,Medical,Male,95,2,Manufacturing Director,2,Single,6032,Yes,15,3,1,2,null
47,No,Travel_Frequently,1309,Sales,4,Medical,Male,99,2,Sales Representative,3,Single,2976,No,19,3,0,0,null
42,No,Travel_Rarely,810,Research & Development,23,Life Sciences,Female,44,4,Research Director,4,Single,15992,No,14,3,0,0,null
29,No,Non-Travel,746,Sales,2,Life Sciences,Male,61,2,Sales Executive,3,Married,4649,No,14,3,0,2,null
42,No,Travel_Rarely,544,Human Resources,2,Technical Degree,Male,52,1,Human Resources,3,Divorced,2696,Yes,11,3,1,0,null
32,No,Travel_Rarely,1062,Research & Development,2,Medical,Female,75,1,Laboratory Technician,2,Married,2370,No,13,3,0,7,null
48,No,Travel_Rarely,530,Sales,29,Medical,Female,91,3,Manager,3,Married,12504,No,21,4,0,0,null
37,No,Travel_Rarely,1319,Research & Development,6,Medical,Male,51,2,Research Scientist,1,Divorced,5974,Yes,13,3,6,7,null
30,No,Non-Travel,641,Sales,25,Technical Degree,Female,85,2,Sales Executive,3,Married,4736,Yes,12,3,2,2,null
26,No,Travel_Rarely,933,Sales,1,Life Sciences,Male,57,2,Sales Executive,3,Married,5296,No,17,3,7,7,null
42,No,Travel_Rarely,1332,Research & Development,2,Other,Male,98,2,Healthcare Representative,4,Single,6781,No,23,4,0,0,null
21,Yes,Travel_Frequently,756,Sales,1,Technical Degree,Female,99,1,Sales Representative,2,Single,2174,Yes,11,3,1,2,null
36,No,Non-Travel,845,Sales,1,Medical,Female,45,2,Sales Executive,4,Single,6653,No,15,3,0,0,null
36,No,Travel_Frequently,541,Sales,3,Medical,Male,48,3,Sales Executive,4,Married,9699,No,11,3,1,12,null
57,No,Travel_Rarely,593,Research & Development,1,Medical,Male,88,2,Healthcare Representative,3,Married,6755,No,11,3,1,2,null
40,No,Travel_Rarely,1171,Research & Development,10,Life Sciences,Female,46,1,Laboratory Technician,3,Married,2213,Yes,13,3,1,7,null
21,No,Non-Travel,895,Sales,9,Medical,Male,39,1,Sales Representative,4,Single,2610,No,24,4,2,2,null
33,Yes,Travel_Rarely,350,Sales,5,Marketing,Female,34,1,Sales Representative,3,Single,2851,Yes,13,3,0,0,null
37,No,Travel_Rarely,921,Research & Development,10,Medical,Female,98,1,Laboratory Technician,1,Married,3452,No,20,4,0,3,null
46,No,Non-Travel,1144,Research & Development,7,Medical,Female,30,2,Manufacturing Director,3,Married,5258,No,14,3,0,0,null
41,Yes,Travel_Frequently,143,Sales,4,Marketing,Male,56,2,Sales Executive,2,Single,9355,No,18,3,7,7,null
50,No,Travel_Rarely,1046,Research & Development,10,Technical Degree,Male,100,3,Healthcare Representative,4,Single,10496,No,15,3,1,3,null
40,Yes,Travel_Rarely,575,Sales,22,Marketing,Male,68,2,Sales Executive,3,Married,6380,Yes,12,3,1,0,null
31,No,Travel_Rarely,408,Research & Development,9,Life Sciences,Male,42,1,Research Scientist,2,Single,2657,Yes,16,3,2,2,null
21,Yes,Travel_Rarely,156,Sales,12,Life Sciences,Female,90,1,Sales Representative,2,Single,2716,No,15,3,0,0,null
29,No,Travel_Rarely,1283,Research & Development,23,Life Sciences,Male,54,1,Research Scientist,4,Single,2201,No,16,3,1,2,null
35,No,Travel_Rarely,755,Research & Development,9,Life Sciences,Male,97,2,Healthcare Representative,2,Single,6540,No,19,3,0,0,null
27,No,Travel_Rarely,1469,Research & Development,1,Medical,Male,82,1,Laboratory Technician,2,Divorced,3816,No,11,3,0,4,null
28,No,Travel_Rarely,304,Sales,9,Life Sciences,Male,92,2,Sales Executive,4,Single,5253,No,16,3,0,7,null
49,No,Travel_Rarely,1261,Research & Development,7,Other,Male,31,3,Healthcare Representative,3,Single,10965,No,24,4,0,0,null
51,No,Travel_Rarely,1178,Sales,14,Life Sciences,Female,87,2,Sales Executive,4,Married,4936,No,11,3,0,7,null
36,No,Travel_Rarely,329,Research & Development,2,Life Sciences,Female,96,1,Research Scientist,3,Married,2543,No,13,3,2,2,null
34,Yes,Non-Travel,1362,Sales,19,Marketing,Male,67,2,Sales Executive,4,Single,5304,Yes,13,3,0,4,null
55,No,Travel_Rarely,1311,Research & Development,2,Life Sciences,Female,97,4,Manager,4,Single,16659,Yes,13,3,1,2,null
24,No,Travel_Rarely,1371,Sales,10,Marketing,Female,77,2,Sales Executive,3,Divorced,4260,Yes,12,3,0,3,null
30,No,Travel_Rarely,202,Sales,2,Technical Degree,Male,72,1,Sales Representative,2,Married,2476,No,18,3,0,0,null
26,Yes,Travel_Frequently,575,Research & Development,3,Technical Degree,Male,73,1,Research Scientist,1,Single,3102,No,22,4,0,4,null
22,No,Travel_Rarely,253,Research & Development,11,Medical,Female,43,1,Research Scientist,2,Married,2244,No,13,3,1,2,null
36,No,Travel_Rarely,164,Sales,2,Medical,Male,61,3,Sales Executive,3,Married,7596,No,13,3,9,0,null
30,Yes,Travel_Frequently,464,Research & Development,4,Technical Degree,Male,40,1,Research Scientist,4,Single,2285,Yes,23,4,0,0,null
37,No,Travel_Rarely,1107,Research & Development,14,Life Sciences,Female,95,1,Laboratory Technician,1,Divorced,3034,No,12,3,12,17,null
40,No,Travel_Rarely,759,Sales,2,Marketing,Female,46,2,Sales Executive,2,Divorced,5715,No,12,3,1,3,null
42,No,Travel_Rarely,201,Research & Development,1,Life Sciences,Female,95,1,Laboratory Technician,1,Divorced,2576,No,16,3,1,2,null
37,No,Travel_Rarely,1305,Research & Development,10,Life Sciences,Male,49,2,Manufacturing Director,2,Single,4197,Yes,12,3,0,1,null
43,No,Travel_Rarely,982,Research & Development,12,Life Sciences,Male,59,4,Research Director,2,Divorced,14336,No,11,3,3,9,null
40,No,Travel_Rarely,555,Research & Development,2,Medical,Female,78,2,Laboratory Technician,3,Married,3448,No,22,4,0,0,null
54,No,Travel_Rarely,821,Research & Development,5,Medical,Male,86,5,Research Director,1,Married,19406,No,11,3,1,2,null
34,No,Non-Travel,1381,Sales,4,Marketing,Female,72,2,Sales Executive,3,Married,6538,No,15,3,1,2,null
31,No,Travel_Rarely,480,Research & Development,7,Medical,Female,31,2,Manufacturing Director,1,Married,4306,No,12,3,3,12,null
43,No,Travel_Frequently,313,Research & Development,21,Medical,Male,61,1,Laboratory Technician,4,Married,2258,No,20,4,1,2,null
43,No,Travel_Rarely,1473,Research & Development,8,Other,Female,74,2,Healthcare Representative,3,Divorced,4522,Yes,14,3,0,2,null
25,No,Travel_Rarely,891,Sales,4,Life Sciences,Female,99,2,Sales Executive,4,Single,4487,Yes,11,3,1,3,null
37,No,Non-Travel,1063,Research & Development,25,Medical,Female,72,2,Research Scientist,3,Married,4449,Yes,15,3,10,7,null
31,No,Travel_Rarely,329,Research & Development,1,Life Sciences,Male,98,1,Laboratory Technician,1,Married,2218,No,12,3,3,2,null

In [0]:
# streaming query
monthly_income_groupby_jobRole = attr_stream_data.groupby("JobRole").agg({"MonthlyIncome": "avg"})
monthly_income_groupby_jobRole.display()

JobRole,avg(MonthlyIncome)
Sales Executive,6105.518518518518
Manufacturing Director,6290.125
Laboratory Technician,3338.866666666667
Sales Representative,2429.0
Healthcare Representative,8267.454545454546
Research Scientist,3675.222222222222
Manager,15566.0
Research Director,15267.5
Human Resources,4553.0

In [0]:
# write data into table ""query_without_checkpoint"" in memory without checkpoint
monthly_income_groupby_jobRole.writeStream\
    .queryName("query_without_checkpoint")\
        .outputMode("complete")\
            .format("memory")\
                .start()

Out[12]: <pyspark.sql.streaming.query.StreamingQuery at 0x7fb4fce4a790>

In [0]:
spark.sql("select * from query_without_checkpoint").display()

JobRole,avg(MonthlyIncome)
Sales Executive,6105.518518518518
Manufacturing Director,6290.125
Laboratory Technician,3338.866666666667
Sales Representative,2429.0
Healthcare Representative,8267.454545454546
Research Scientist,3675.222222222222
Manager,15566.0
Research Director,15267.5
Human Resources,4553.0

In [0]:
# write data into table "query_checkpoint" in memory with saving results in "dbfs:/FileStore/checkpoint/"
# the results saved in this table are resilient to failure
monthly_income_groupby_jobRole.writeStream\
    .queryName("query_checkpoint")\
        .outputMode("complete")\
            .option("checkpointLocation", "dbfs:/FileStore/checkpoint_1/")\
                .format("memory")\
                    .start()

Out[14]: <pyspark.sql.streaming.query.StreamingQuery at 0x7fb4fc900af0>

In [0]:
spark.sql("select * from query_checkpoint").display()